---
name: validate-deployer-role-module

on:
  push:
    paths:
      - integration-tests/modules/deployer-role/**/*
      - .github/workflows/validate-deployer-role.yml

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
      - name: Check formatting
        working-directory: integration-tests/modules/deployer-role
        run: |
          terraform fmt -check -recursive
      - name: Terraform validate
        working-directory: integration-tests/modules/deployer-role
        run: |
          terraform init -no-color
          terraform validate -no-color
